language: node_js
node_js:
  - "9"
  - "8"
  - "7"
before_script:
  - sudo apt install mecab libmecab-dev mecab-ipadic-utf8
install:
  - npm install -g codecov istanbul
script:
  - npm install
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter test -- -R spec
  - codecov
 addons:
    apt:
      update: true
      
